# Generated by Django 5.1.2 on 2024-10-22 23:59

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('iban', models.TextField(unique=True)),
                ('balance', models.IntegerField())
            ],
        ),
    ]