# Generated by Django 5.1.2 on 2024-10-22 23:59

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfoTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EfoTermSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('efo_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='api.efoterm')),
            ],
        ),
    ]
