name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Backend Docker image
      run: |
        docker build ./django-backend \
          --file django-backend/Dockerfile \
          --tag backend:$(date +%s)
    
    - name: Build Frontend Docker image
      run: |
        docker build ./react-frontend \
          --file react-frontend/Dockerfile \
          --tag frontend:$(date +%s)
